language: node_js

node_js:
    - 7

notifications:
    email: false

cache:
    apt: true
    directories:
        - $HOME/.npm
        - $HOME/.cache/bower

addons:
    apt:
        packages:
            # Required to output karma-coverage summary
            - lcov

sudo: false

before_install:
    - npm install -g bower grunt-cli codecov

before_script:
    # Start webserver before other tasks so it has time to boot.
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - yes no | bower install --verbose

script:
    - grunt travis
    # Fail if dist has not been compiled:
    # - compile the dist
    - grunt build
    # - show a diff if it's there
    - git diff dist/
    # - programmatically check presence of dist changes: it will exit 1 if found
    - git diff-index --quiet HEAD -- dist/

after_success:
    # Print coverage in Travis log
    - lcov -l coverage/lcov.info
    # Upload to codecov.io
    - codecov
